version: "2"

services:
  smartcar:
    image: lucpfi/smartcar:5.0.1
    environment:
      - senec_host
      - plug
      - min_power_overflow
      - interval
    network_mode: host
    privileged: true
    restart: unless-stopped